### ISSUE TITLE
i meet a error:    TypeError: separable_convolution2d() got an unexpected keyword argument 'data_format'

### ISSUE THREAD

**Issue by chl916185** [Zehaos/MobileNet#49]
Your tensorflow is which version?
i meet a error:
   TypeError: separable_convolution2d() got an unexpected keyword argument 'data_format'
@Zehaos

**Comment by Zehaos** [comment]
Hi, @chl916185 
1.0.1, 1.1.0 should work.

**Comment by martinkersner** [comment]
@chl916185 I think it works only with Tensorflow 1.4.

**Comment by post2web** [comment]
The error disappeared after I upgraded from tensorflow 1.3 to 1.4

**Comment by 15556535718** [comment]
I meet an error!   
TypeError:separable_conv2d() got an unexpected keyword argument 'rate'.
My tensorflow-gpu version is (0.12.1).
This question is caused by tensorflow vision????   thank
